In [1]:
import pandas as pd
matches = pd.read_csv('data/atp_matches_2023.csv')
print(matches.shape)
matches.head()

(2986, 49)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,...,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
1,2023-9900,United Cup,Hard,18,A,20230102,299,126207,NaN,NaN,...,12.0,8.0,3.0,4.0,1.0,3.0,19.0,2000.0,23.0,1865.0
2,2023-9900,United Cup,Hard,18,A,20230102,296,126203,3.0,NaN,...,62.0,51.0,7.0,12.0,2.0,2.0,9.0,3355.0,10.0,2905.0
3,2023-9900,United Cup,Hard,18,A,20230102,295,126207,NaN,NaN,...,41.0,26.0,12.0,9.0,6.0,9.0,19.0,2000.0,245.0,220.0
4,2023-9900,United Cup,Hard,18,A,20230102,292,126774,1.0,NaN,...,58.0,48.0,18.0,16.0,1.0,2.0,4.0,5550.0,16.0,2375.0

In [2]:
# all 2021 tour matches
matches = pd.read_csv('data/atp_matches_2021.csv')
# all the 2021 challenger/qualifying matches
chall = pd.read_csv('data/atp_matches_qual_chall_2021.csv')
# stacking both fo those (matches and chall) into one table
all_matches_2021 = pd.concat([matches, chall], ignore_index=True)


print(all_matches_2021.shape)

(10230, 49)

In [3]:
# takes just the winner and loser ID columns from all 2021 matches, and make a separate copy
winners_view = all_matches_2021[['winner_id', 'loser_id']].copy()
# relabel the columns from loser and winner to opponent and player
winners_view = winners_view.rename(columns={'winner_id': 'player_id', 'loser_id': 'opponent_id'})
# mark Won = true  for the person who won
winners_view['won'] = True

winners_view.head()

   player_id  opponent_id   won
0     126207       126952  True
1     105526       106329  True
2     111576       104797  True
3     105357       207518  True
4     207830       105311  True

In [4]:
# take just the winner and loser Id columns again
losers_view = all_matches_2021[['winner_id', 'loser_id']].copy()
# relabel columns (won describes player_id)
losers_view = losers_view.rename(columns={'loser_id': 'player_id', 'winner_id': 'opponent_id'})
losers_view['won'] = False
losers_view.head()

   opponent_id  player_id    won
0       126207     126952  False
1       105526     106329  False
2       111576     104797  False
3       105357     207518  False
4       207830     105311  False

In [5]:
# stack winner and losers table into one
player_matches = pd.concat([winners_view, losers_view], ignore_index=True)
print(player_matches.shape)

(20460, 3)

In [6]:
player_matches.head()

   player_id  opponent_id   won
0     126207       126952  True
1     105526       106329  True
2     111576       104797  True
3     105357       207518  True
4     207830       105311  True

In [7]:
players = pd.read_csv('data/atp_players.csv')
players[players['name_last'] == 'Alcaraz']  # filter by last name to find alcaraz

/var/folders/rk/w0plzk6n4033x_g087swl6t40000gn/T/ipykernel_94175/3246681681.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('data/atp_players.csv')

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
3577,103578,Antonio,Alcaraz,U,19800621.0,ESP,NaN,NaN
23371,123387,Arius,Alcaraz,U,19720825.0,PHI,NaN,NaN
60275,207989,Carlos,Alcaraz,R,20030505.0,ESP,183.0,Q85518537

In [14]:
# group all rows by player_id, then average the won column (True=1, False=0)
win_rates = player_matches.groupby('player_id')['won'].mean()

# look up a players win rate
print("Carlos Alcaraz win rate is: ", win_rates.loc[207989])

Carlos Alcaraz win rate is:  0.7164179104477612

In [15]:
# add the tournament date for each player in player_matches
player_matches['tourney_date'] = pd.to_datetime(player_matches['tourney_date'], format='%Y%m%d')

print(player_matches.shape)
player_matches.head()

(20460, 4)

   player_id  opponent_id tourney_date   won
0     126207       126952   2021-07-24  True
1     105526       106329   2021-07-24  True
2     111576       104797   2021-07-24  True
3     105357       207518   2021-07-24  True
4     207830       105311   2021-07-24  True

In [16]:
import glob

# find every ranking file in the data folder
rank_files = glob.glob('data/atp_rankings_*.csv')

# load all of the files and stack them into one big rankings table
rankings = pd.concat([pd.read_csv(f) for f in rank_files], ignore_index=True)

# convert the ranking date into a readable format
rankings['ranking_date'] = pd.to_datetime(rankings['ranking_date'], format='%Y%m%d')

# sort each player match by the tournament date
player_matches_sorted = player_matches.sort_values('tourney_date')

# sort the rankings of each player by the ranking date
rankings_sorted = rankings.sort_values('ranking_date')

player_matches_sorted.head()

      player_id  opponent_id tourney_date   won
3604     105933       105271   2021-01-04  True
1160     126205       106227   2021-01-04  True
1161     111815       111574   2021-01-04  True
1162     106216       110536   2021-01-04  True
1163     126207       105385   2021-01-04  True

In [17]:
player_matches_sorted.dtypes

player_id                int64
opponent_id              int64
tourney_date    datetime64[ns]
won                       bool
dtype: object

In [18]:
# merge each match with the opponent's most recent ranking as of that match date
# look for every match what the opponent's ranking was on the most recent date before the match
# find the opponents rank without needing an exact match date
opponent_ranks = pd.merge_asof(
    player_matches_sorted, # the 1st table (players) (left table)
    rankings_sorted, # the 2nd table (lookup table for rankings) (right table)
    left_on = 'tourney_date', # in table 1, find the date
    right_on = 'ranking_date', # in table 2, find the date
    left_by = 'opponent_id', # lookup opponent in table 1
    right_by = 'player', # look for player that opponent_id matches
    direction = 'backward' # for ex, if march 25 tourney happened, choose the march 22nd date instead of march 29th
)

opponent_ranks.head()

,player_id,opponent_id,tourney_date,won,ranking_date,rank,player,points
0,105933,105271,2021-01-04,True,2021-01-04,435.0,105271.0,87.0
1,126205,106227,2021-01-04,True,2021-01-04,268.0,106227.0,205.0
2,111815,111574,2021-01-04,True,2021-01-04,299.0,111574.0,165.0
3,106216,110536,2021-01-04,True,2021-01-04,304.0,110536.0,154.0
4,126207,105385,2021-01-04,True,2021-01-04,327.0,105385.0,135.0

In [19]:
opponent_ranks[opponent_ranks['opponent_id'] == 207989][['opponent_id', 'tourney_date', 'rank']].head()

     opponent_id tourney_date   rank
176       207989   2021-01-10  141.0
181       207989   2021-01-10  141.0
247       207989   2021-01-10  141.0
891       207989   2021-02-01  146.0
914       207989   2021-02-01  146.0

In [20]:
opponent_ranks.shape

(20460, 8)

In [21]:
# look for every match what the player's ranking was on the most recent date before the match
player_ranks = pd.merge_asof(
    player_matches_sorted,
    rankings_sorted,
    left_on = 'tourney_date',
    right_on = 'ranking_date',
    left_by = 'player_id',
    right_by = 'player',
    direction = 'backward'
)

player_ranks.head()

,player_id,opponent_id,tourney_date,won,ranking_date,rank,player,points
0,105933,105271,2021-01-04,True,2021-01-04,293.0,105933.0,171.0
1,126205,106227,2021-01-04,True,2021-01-04,52.0,126205.0,1080.0
2,111815,111574,2021-01-04,True,2021-01-04,74.0,111815.0,877.0
3,106216,110536,2021-01-04,True,2021-01-04,274.0,106216.0,195.0
4,126207,105385,2021-01-04,True,2021-01-04,62.0,126207.0,1005.0

In [22]:
# add opponent rank to player_ranks
player_ranks['opponent_rank'] = opponent_ranks['rank']
player_ranks.head()

,player_id,opponent_id,tourney_date,won,ranking_date,rank,player,points,opponent_rank
0,105933,105271,2021-01-04,True,2021-01-04,293.0,105933.0,171.0,435.0
1,126205,106227,2021-01-04,True,2021-01-04,52.0,126205.0,1080.0,268.0
2,111815,111574,2021-01-04,True,2021-01-04,74.0,111815.0,877.0,299.0
3,106216,110536,2021-01-04,True,2021-01-04,274.0,106216.0,195.0,304.0
4,126207,105385,2021-01-04,True,2021-01-04,62.0,126207.0,1005.0,327.0

In [23]:
# filter by players who played against ppl with better rankings than them
vs_higher_ranked = player_ranks[player_ranks['rank'] > player_ranks['opponent_rank']]
print(vs_higher_ranked.shape)
vs_higher_ranked.head()

(10097, 9)

,player_id,opponent_id,tourney_date,won,ranking_date,rank,player,points,opponent_rank
5,103333,104665,2021-01-04,True,2021-01-04,148.0,103333.0,444.0,59.0
6,105933,111511,2021-01-04,True,2021-01-04,293.0,105933.0,171.0,251.0
7,123755,105413,2021-01-04,True,2021-01-04,115.0,123755.0,606.0,100.0
10,106328,144869,2021-01-04,True,2021-01-04,789.0,106328.0,22.0,256.0
12,200624,126205,2021-01-04,True,2021-01-04,119.0,200624.0,566.0,52.0

In [24]:
# find the win rate of ppl who played against ppl that are higher ranked
win_rate_vs_higher_ranked = vs_higher_ranked.groupby('player_id')['won'].mean()
# Alcaraz's win rate
print(win_rate_vs_higher_ranked.loc[207989])

0.6060606060606061

In [25]:
def get_rank(player_id, date):
    #Player's ranking on the most recent ranking date on or before the date
    r = rankings[(rankings['player'] == player_id) & (rankings['ranking_date'] <= date)]
    if r.empty:
        return None
    return r.sort_values('ranking_date').iloc[-1]['rank']

In [26]:
rankings.shape

(3420595, 4)

In [27]:
# find the numebr of players that have been 
players_2021 = player_matches['player_id'].unique()
print(len(players_2021))

1033

In [28]:
# early jan is start of szn
season_start_date = pd.Timestamp('2021-01-10')

# for every unique player from 2021, look up their rank on that szn start date
# pid = player id
rank_start_list = [
    {'player_id': pid, 'rank_start': get_rank(pid, season_start_date)}
    for pid in players_2021
]

# turn that list of {player_id, rank_start} records into a proper table
rank_start_df = pd.DataFrame(rank_start_list)

print(rank_start_df.shape)
rank_start_df.head()

(1033, 2)

   player_id  rank_start
0     126207        62.0
1     105526        37.0
2     111576       137.0
3     105357        38.0
4     207830       197.0

In [29]:
winners_view = all_matches_2021[['winner_id', 'loser_id', 'tourney_date']].copy()
winners_view = winners_view.rename(columns={'winner_id': 'player_id', 'loser_id': 'opponent_id'})
winners_view['won'] = True

losers_view = all_matches_2021[['winner_id', 'loser_id', 'tourney_date']].copy()
losers_view = losers_view.rename(columns={'loser_id': 'player_id', 'winner_id': 'opponent_id'})
losers_view['won'] = False

player_matches = pd.concat([winners_view, losers_view], ignore_index=True)
player_matches['tourney_date'] = pd.to_datetime(player_matches['tourney_date'], format='%Y%m%d')

print(player_matches.columns)
print(player_matches.shape)

Index(['player_id', 'opponent_id', 'tourney_date', 'won'], dtype='object')
(20460, 4)

In [31]:
players = pd.read_csv('data/atp_players.csv')
players['dob'] = pd.to_datetime(players['dob'], format='%Y%m%d', errors='coerce')

players['age_years'] = (season_start_date - players['dob']).dt.days / 365.25

players[['player_id', 'name_first', 'name_last', 'dob', 'age_years']].head()

/var/folders/rk/w0plzk6n4033x_g087swl6t40000gn/T/ipykernel_94175/3056247165.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('data/atp_players.csv')

   player_id name_first name_last        dob   age_years
0     100001    Gardnar    Mulloy 1913-11-22  107.134839
1     100002     Pancho    Segura 1921-06-20   99.559206
2     100003      Frank   Sedgman 1927-10-02   93.275838
3     100004   Giuseppe     Merlo 1927-10-11   93.251198
4     100005    Richard  Gonzalez 1928-05-09   92.673511

In [32]:
players[players['player_id'] == 207989][['name_first', 'name_last', 'dob', 'age_years']]

      name_first name_last        dob  age_years
60275     Carlos   Alcaraz 2003-05-05  17.686516

In [33]:
season_data = rank_start_df.merge(players[['player_id', 'age_years']], on='player_id', how='left')
season_data.head()

   player_id  rank_start  age_years
0     126207        62.0  22.973306
1     105526        37.0  30.713210
2     111576       137.0  23.403149
3     105357        38.0  31.575633
4     207830       197.0  20.243669

In [34]:
match_counts = player_matches.groupby('player_id').size().reset_index(name='matches_played')
season_data = season_data.merge(match_counts, on='player_id', how='left')
season_data.head()

   player_id  rank_start  age_years  matches_played
0     126207        62.0  22.973306              69
1     105526        37.0  30.713210              57
2     111576       137.0  23.403149              49
3     105357        38.0  31.575633              50
4     207830       197.0  20.243669              47

In [35]:
eligible = season_data[
    (season_data['rank_start'] >= 75) &
    (season_data['rank_start'] <= 300) &
    (season_data['age_years'] <= 24) &
    (season_data['matches_played'] >= 20)
]
print(eligible.shape)
eligible.head()

(51, 4)

    player_id  rank_start  age_years  matches_played
2      111576       137.0  23.403149              49
4      207830       197.0  20.243669              47
23     126845       238.0  22.773443              34
55     117360       124.0  23.693361              43
56     200384       161.0  20.290212              74

In [36]:
get_rank(111576, pd.Timestamp('2022-12-26'))

np.int64(502)

In [37]:
rank_start = 137.0
next_rank = 502

breakout = (next_rank <= rank_start / 2) or (next_rank <= 50)
print(breakout)

False

In [38]:
next_season_end = pd.Timestamp('2022-12-26')

breakout_list = []
for pid, rank_start in zip(eligible['player_id'], eligible['rank_start']):
    next_rank = get_rank(pid, next_season_end)
    if next_rank is None:
        breakout = None  # no ranking data next season (retired, injured, etc.)
    else:
        breakout = (next_rank <= rank_start / 2) or (next_rank <= 50)
    breakout_list.append({'player_id': pid, 'next_rank': next_rank, 'breakout': breakout})

breakout_df = pd.DataFrame(breakout_list)
breakout_df.head()

   player_id  next_rank  breakout
0     111576        502     False
1     207830         97      True
2     126845        220     False
3     117360        334     False
4     200384        108     False

In [39]:
breakout_df['breakout'].value_counts()

breakout
False    36
True     15
Name: count, dtype: int64

In [46]:
year = 2015
matches = pd.read_csv(f'data/atp_matches_{year}.csv')
chall = pd.read_csv(f'data/atp_matches_qual_chall_{year}.csv')
all_matches = pd.concat([matches, chall], ignore_index=True)

winners = all_matches[['winner_id', 'loser_id', 'tourney_date']].rename(
    columns={'winner_id': 'player_id', 'loser_id': 'opponent_id'})
winners['won'] = True
losers = all_matches[['winner_id', 'loser_id', 'tourney_date']].rename(
    columns={'loser_id': 'player_id', 'winner_id': 'opponent_id'})
losers['won'] = False
pm = pd.concat([winners, losers], ignore_index=True)
pm['tourney_date'] = pd.to_datetime(pm['tourney_date'], format='%Y%m%d')
pm_sorted = pm.sort_values('tourney_date')

In [48]:
opp = pd.merge_asof(pm_sorted, rankings_sorted, left_on='tourney_date', right_on='ranking_date',
                     left_by='opponent_id', right_by='player', direction='backward')
own = pd.merge_asof(pm_sorted, rankings_sorted, left_on='tourney_date', right_on='ranking_date',
                     left_by='player_id', right_by='player', direction='backward')
own['opponent_rank'] = opp['rank']

In [50]:
def build_season_data(year):
    season_start_date = pd.Timestamp(f'{year}-01-10')
    next_season_end = pd.Timestamp(f'{year+1}-12-26')

    matches = pd.read_csv(f'data/atp_matches_{year}.csv')
    chall = pd.read_csv(f'data/atp_matches_qual_chall_{year}.csv')
    all_matches = pd.concat([matches, chall], ignore_index=True)

    winners = all_matches[['winner_id', 'loser_id', 'tourney_date']].rename(
        columns={'winner_id': 'player_id', 'loser_id': 'opponent_id'})
    winners['won'] = True
    losers = all_matches[['winner_id', 'loser_id', 'tourney_date']].rename(
        columns={'loser_id': 'player_id', 'winner_id': 'opponent_id'})
    losers['won'] = False
    pm = pd.concat([winners, losers], ignore_index=True)
    pm['tourney_date'] = pd.to_datetime(pm['tourney_date'], format='%Y%m%d')
    pm_sorted = pm.sort_values('tourney_date')

    opp = pd.merge_asof(pm_sorted, rankings_sorted, left_on='tourney_date', right_on='ranking_date',
                         left_by='opponent_id', right_by='player', direction='backward')
    own = pd.merge_asof(pm_sorted, rankings_sorted, left_on='tourney_date', right_on='ranking_date',
                         left_by='player_id', right_by='player', direction='backward')
    own['opponent_rank'] = opp['rank']

    win_rate = pm.groupby('player_id')['won'].mean().reset_index(name='win_rate')
    vs_higher = own[own['rank'] > own['opponent_rank']]
    win_rate_vs_higher = vs_higher.groupby('player_id')['won'].mean().reset_index(name='win_rate_vs_higher')
    match_counts = pm.groupby('player_id').size().reset_index(name='matches_played')

    player_ids = pm['player_id'].unique()
    rank_start = pd.DataFrame([{'player_id': p, 'rank_start': get_rank(p, season_start_date)} for p in player_ids])
    age = players[['player_id', 'dob']].copy()
    age['age_years'] = (season_start_date - age['dob']).dt.days / 365.25

    df = rank_start.merge(win_rate, on='player_id', how='left')
    df = df.merge(win_rate_vs_higher, on='player_id', how='left')
    df = df.merge(age[['player_id', 'age_years']], on='player_id', how='left')
    df = df.merge(match_counts, on='player_id', how='left')

    eligible = df[(df['rank_start'] >= 75) & (df['rank_start'] <= 300) &
                  (df['age_years'] <= 24) & (df['matches_played'] >= 20)].copy()

    eligible['next_rank'] = eligible.apply(lambda r: get_rank(r['player_id'], next_season_end), axis=1)
    eligible['breakout'] = eligible.apply(
        lambda r: None if pd.isna(r['next_rank']) else (r['next_rank'] <= r['rank_start']/2 or r['next_rank'] <= 50),
        axis=1)
    eligible['season'] = year

    return eligible

In [51]:
result_2015 = build_season_data(2015)
print(result_2015.shape)
result_2015.head()

(58, 9)

,player_id,rank_start,win_rate,win_rate_vs_higher,age_years,matches_played,next_rank,breakout,season
2,105902,125.0,0.550000,0.352941,22.970568,60,103,False,2015
9,106423,149.0,0.618182,0.437500,18.751540,55,1031,False,2015
16,106432,95.0,0.538462,0.333333,18.154689,65,48,True,2015
17,111200,227.0,0.540984,0.486486,18.751540,61,160,False,2015
33,105932,171.0,0.593220,0.428571,22.880219,59,94,False,2015

In [53]:
result_2018 = build_season_data(2018)
result_2023 = build_season_data(2023)
result_2021 = build_season_data(2021)

all_seasons = pd.concat([result_2015, result_2018, result_2021, result_2023], ignore_index=True)
print(all_seasons.shape)
all_seasons['breakout'].value_counts()

(247, 9)

breakout
False    181
True      66
Name: count, dtype: int64

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model_data = all_seasons.dropna(subset=['win_rate', 'win_rate_vs_higher', 'age_years', 'rank_start', 'breakout'])

X = model_data[['win_rate', 'win_rate_vs_higher', 'age_years', 'rank_start']]
y = model_data['breakout'].astype(int)

model = LogisticRegression()
model.fit(X, y)

preds = model.predict(X)
print(classification_report(y, preds))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87       181
           1       0.73      0.29      0.41        66

    accuracy                           0.78       247
   macro avg       0.76      0.62      0.64       247
weighted avg       0.77      0.78      0.74       247

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

features = ['win_rate', 'win_rate_vs_higher', 'age_years', 'rank_start']
model_data = all_seasons.dropna(subset=features + ['breakout'])

train = model_data[model_data['season'].isin([2015, 2018])]
test = model_data[model_data['season'].isin([2021, 2023])]

model = LogisticRegression(max_iter=1000)
model.fit(train[features], train['breakout'].astype(int))

preds = model.predict(test[features])
print(classification_report(test['breakout'].astype(int), preds))

              precision    recall  f1-score   support

           0       0.72      0.99      0.83        82
           1       0.80      0.11      0.20        36

    accuracy                           0.72       118
   macro avg       0.76      0.55      0.51       118
weighted avg       0.74      0.72      0.64       118

In [56]:
from sklearn.metrics import roc_auc_score

probs = model.predict_proba(test[features])[:, 1]
print(roc_auc_score(test['breakout'].astype(int), probs))

0.7113821138211383

In [57]:
test = test.copy()
test['score'] = probs
top = test.sort_values('score', ascending=False).head(10)
print(top[['player_id', 'season', 'rank_start', 'score', 'breakout']])
print(top['breakout'].astype(int).mean())

     player_id  season  rank_start     score  breakout
143     207989    2021       141.0  0.745134      True
145     207518    2021       129.0  0.567798      True
186     209992    2023       194.0  0.545230      True
197     209414    2023       142.0  0.535556     False
144     200624    2021       119.0  0.508395      True
147     206909    2021       170.0  0.493900      True
181     208103    2023        78.0  0.487176      True
184     210097    2023        92.0  0.483148      True
208     208502    2023       119.0  0.458992     False
192     209950    2023       252.0  0.429915      True
0.8